---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year/format
- type: list
  name: categories
  label: categories
  config:
    use_select: false
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
pages:
- projects/cma558.md
- projects/correspondence.md
- projects/cryptonite.md
- projects/dots.md
- projects/mansa-musa.md
- projects/mentalism.md
- projects/molecular-gastronomy.md
- projects/ok.md
- projects/orbs.md
- projects/solar-path.md
- projects/the-london-book-fair.md
- projects/°-jupiter-calendar.md
