---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year/format
- type: list
  name: categories
  label: categories
  config:
    use_select: false
pages:
- projects/dots.md
- projects/molecular-gastronomy.md
- projects/the-london-book-fair.md
- projects/°-jupiter-calendar.md
